### ISSUE TITLE
Error in mtrand.RandomState.choice

### ISSUE THREAD

**Issue by hanshong** [LordLiang/FVNet#4]
I have successfully run preprocess_car_person.py, and generated the .npy in cropped directory.
But while I run train.py, it still has a problem like this:

/root/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:73: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
Traceback (most recent call last):
  File "train.py", line 385, in <module>
    train()
  File "train.py", line 195, in train
    train_one_epoch(sess, ops, train_writer)
  File "train.py", line 235, in train_one_epoch
    get_batch(TRAIN_DATASET, train_idxs, start_idx, end_idx, NUM_CHANNEL)
  File "/home/FVNet/est-kittinet/kitti/kitti_dataset.py", line 113, in get_batch
    sample = dataset[idxs[(i + start_idx) % num]]
  File "/home/FVNet/est-kittinet/kitti/kitti_dataset.py", line 47, in __getitem__
    replace=(object_rect.shape[0] < self.num_point))
  File "mtrand.pyx", line 1120, in mtrand.RandomState.choice
ValueError: a must be greater than 0

Do you have met the problem before? Should I normalize some data? Hope for help, thanks.

**Comment by LordLiang** [comment]
you need to filter some samples which have on points, I will submit the code for filtering today...



---Original---
